# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json
kind: AIchorManifest
apiVersion: 0.2.1
builder:
  image: winnow
  dockerfile: ./Dockerfile
  context: .
  buildArgs:
    USE_CUDA: "true"

spec:
  debug:
      vscode:
        enabled: true # required
        path: "/aichor/code" # Optional, defaults to "code". Refer the absolute path of the binary if not findable in $PATH
        provider: "github" # Optional, vscode tunnel provider. Options are "github" or "microsoft", defaults to "github"
  operator: jobset
  image: winnow
  command: make set-gcp-credentials && make set-foundation-model-ceph-credentials && make download_marco_dataset && make download_marco_beams && make download-model

  types:
    worker:
      count: 1
      resources:
        cpus: 8
        ramRatio: 8 # >= 2
