[project]
name = "winnow"
authors = [{name="InstaDeep"}]
description = "Score calibration and false discovery estimation for de novo peptide sequencing."
readme = "README.md"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "instanovo>=1.1.1",
    "ipywidgets>=8.1.5",
    "jax>=0.5.2",
    "koinapy>=0.0.10",
    "numpyro>=0.17.0",
    "tensorflow-probability>=0.25.0",
    "numba==0.60.0",
    "tomli>=2.2.1",
    "typer>=0.15.2",
    "marimo>=0.13.9",
    "altair>=5.5.0",
    "vegafusion[embed]>=2.0.2",
    "vl-convert-python>=1.6.0",
    "flax>=0.10.6",
    "ray[data, default]>=2.46.0",
    "py-spy>=0.4.0",
    "scikit-learn>=1.6.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["winnow"]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "ipykernel>=6.29.5",
    "tensorboard-plugin-profile>=2.19.9",
    "tensorflow>=2.18.1",
    "python-dotenv>=1.1.0",
    "py-spy>=0.4.0",
]

cuda = [
    "jax[cuda]>=0.5.2",
    "jaxlib>=0.5.2",
]

[project.scripts]
winnow='winnow.scripts.main:app'
