[project]
name = "winnow"
authors = [{name="InstaDeep"}]
description = "Score calibration and false discovery estimation for de novo peptide sequencing."
readme = "README.md"
version = "1.0.0"
dynamic = ["dependencies", "optional-dependencies"]
requires-python = "==3.9.*"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["winnow"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements/requirements.in"]}
optional-dependencies.dev = {file = ["requirements/requirements-dev.txt"]}

[tool.uv]
override-dependencies = ["seaborn==0.12.2"]

[project.scripts]
winnow='winnow.scripts.main:app'
