[project]
name = "winnow"
authors = [{name="InstaDeep"}]
description = "Score calibration and false discovery estimation for de novo peptide sequencing."
readme = "README.md"
version = "1.0.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["winnow"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}