[project]
name = "winnow"
authors = [{name="InstaDeep"}]
description = "Score calibration and false discovery estimation for de novo peptide sequencing."
readme = "README.md"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "instanovo",
    "jax>=0.5.2",
    "koinapy>=0.0.10",
    "numpyro>=0.17.0",
    "tensorflow-probability>=0.25.0",
    "numba==0.60.0",
    "tomli>=2.2.1",
    "typer>=0.15.2",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["winnow"]

[tool.uv.sources]
instanovo = { git = "ssh://git@gitlab.com/instadeep/dtu-denovo-sequencing.git" }

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
]

[project.scripts]
winnow='winnow.scripts.main:app'

[project.optional-dependencies]
notebook = [
    "huggingface-hub>=0.29.3",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "jupyter>=1.1.1",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
