spectrum_path: validation_datasets_corrected/spectrum_data/labelled/dataset-helaqc-annotated-0000-0001.parquet
beam_predictions_path: validation_datasets_corrected/beam_preds/labelled/helaqc-annotated_beam_preds.csv
