spectrum_path: validation_datasets_corrected/spectrum_data/labelled/dataset-snakevenoms-annotated-0000-0001.parquet
beam_predictions_path: validation_datasets_corrected/beam_preds/labelled/snakevenoms-annotated_beam_preds.csv
