spectrum_path: validation_datasets_corrected/spectrum_data/labelled/test_spectrum_all_datasets.parquet
beam_predictions_path: validation_datasets_corrected/beam_preds/labelled/test_beam_all_datasets.csv
