name: Build
description:
  Make a proposal or report an issue related to the build system or external dependencies.
title: "build: "
labels: ["build"]

body:
  - type: textarea
    attributes:
      label: "Summary:"
      description: >
        Provide a brief summary of the build change.

  - type: textarea
    attributes:
      label: "Description & Purpose:"
      description: >
        Describe in more detail the build change and the purpose it will serve.

  - type: textarea
    attributes:
      label: "Implementation Overview:"
      description: >
        Checklist for steps required to implement the change.

  - type: textarea
    attributes:
      label: "Additional Notes:"
      description: >
        Any additional notes.
