name: Tests
description: Make a proposal or report an issue related to the test suite.
title: "test: "
labels: ["test"]

body:
  - type: textarea
    attributes:
      label: "Summary:"
      description: >
        Provide a brief summary of the tests to be added/updated.

  - type: textarea
    attributes:
      label: "Description & Purpose:"
      description: >
        Describe in more detail the test update.

  - type: textarea
    attributes:
      label: "Additional Notes:"
      description: >
        Any additional notes.
