data:
  bucket_path: 's3://winnow-g88rh'
  train_path: 'transformer/val.parquet'
  val_path: 'transformer/debug.parquet'
  num_blocks: 1200
model:
  spectrum_encoder:
    dim_model: 256
    num_heads: 8
    dim_feedforward: 512
    num_layers: 8
    dropout_rate: 0.0
  peptide_encoder:
    dim_residue: 256
    dim_modification: 256
    dim_model: 256
    num_self_heads: 8
    num_condition_heads: 8
    dim_feedforward: 512
    num_layers: 8
    max_len: 1000
    dropout_rate: 0.0
  seed: 42
training:
  num_epochs: 1
  batch_size: 8
  eval_batch_size: 8
  learning_rate: 0.0001
  eval_frequency: 20
  patience: 20
  num_peaks: 200
logging:
  neptune_project: InstaDeep/OnTrack-77
  log_file: 'logs/deep_calibration.log'
  ray_timeline_path: 'logs/ray_timeline_long.json'
checkpointing:
  checkpoint_path: '/app/checkpoints/deep'
