name: Run pre-commit hooks on all files
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.6"
      - name: Install dependencies
        run: uv sync --only-dev
      - name: Run pre-commit hooks
        run: uv run --only-dev pre-commit run --all-files
