name: Run pre-commit hooks on all files
on:
  push:

jobs:
  docker-build:
    uses: instadeepai/mlops-reusable-ci/.github/workflows/docker-build.yaml@main
    with:
      display-name: Test image
      build-path: . #project root
      image: ghcr.io/instadeepai/winnow/test
      cache-image: ghcr.io/instadeepai/winnow/test/cache
      filename: "./Dockerfile.test"
      registry-host: ghcr.io
      registry-username: ${{ github.actor }}
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
      dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}

  lint:
    needs: docker-build
    runs-on: instadeep-ci
    container: # This is a mandatory step
      image: ghcr.io/instadeepai/winnow/test:${{ github.sha }} # Image name can't include environment variables
      credentials: # required if the image is in a private registry
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      # Workaround for https://github.com/actions/checkout/issues/1169
      - run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - name: Run pre-commit hooks
        run: uv run --only-dev pre-commit run --all-files
